# -*- coding: utf-8 -*-
"""Yolo model for PMipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ozce_xuKVDD38QCIwFmb6VxZLlIYRLLM
"""

get_ipython().system('pip install ultralytics --quiet')
get_ipython().system('pip install pyyaml --quiet')

import os, sys, json, shutil, random, zipfile, yaml
from pathlib import Path
from google.colab import files
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
from IPython.display import Image, display, clear_output

print("✅ All packages installed")
print("✅ Libraries imported")

print("📂 Please upload your Label Studio 'YOLO with Images' ZIP file...")
uploaded = files.upload()

ZIP_PATH = list(uploaded.keys())[0]
print(f"\n✅ Uploaded: {ZIP_PATH}  ({os.path.getsize(ZIP_PATH)/1024:.1f} KB)")

EXTRACT_DIR = Path("/content/ls_export")
EXTRACT_DIR.mkdir(exist_ok=True)

with zipfile.ZipFile(ZIP_PATH, "r") as zf:
    zf.extractall(EXTRACT_DIR)

print("📁 ZIP contents:")
for p in sorted(EXTRACT_DIR.rglob("*")):
    depth  = len(p.relative_to(EXTRACT_DIR).parts) - 1
    indent = "   " * depth
    suffix = "/" if p.is_dir() else f"  ({p.stat().st_size} bytes)"
    print(f"   {indent}{p.name}{suffix}")

CLASSES = []
for f in EXTRACT_DIR.rglob("classes.txt"):
    CLASSES = [l.strip() for l in open(f) if l.strip()]
    if CLASSES:
        print(f"📋 Classes from classes.txt: {CLASSES}")
        break

# ── Try notes.json ───────────────────────────────────────────────
if not CLASSES:
    for f in EXTRACT_DIR.rglob("notes.json"):
        try:
            data = json.load(open(f))
            CLASSES = data.get("categories", [])
            if CLASSES:
                print(f"📋 Classes from notes.json: {CLASSES}")
                break
        except Exception:
            pass

# ── Manual fallback — EDIT THIS LIST if auto-detection failed ────
if not CLASSES:
    CLASSES = [
        "crack",
        "scratch",
        "rough_edge",
        "porosity",
        "machining_burr",
    ]
    print(f"⚠️  Auto-detection failed. Using fallback classes: {CLASSES}")
    print("   → Edit CLASSES list above if these are wrong!")

print(f"\n✅ {len(CLASSES)} classes: {CLASSES}")

DATASET_DIR  = Path("/content/dataset")
TRAIN_RATIO  = 0.8    # 80% train, 20% val
RANDOM_SEED  = 42

IMAGE_EXTS = {".jpg", ".jpeg", ".png", ".bmp", ".webp", ".tiff", ".tif"}

# ── Find all images ──────────────────────────────────────────────
all_images = [p for p in EXTRACT_DIR.rglob("*")
              if p.suffix.lower() in IMAGE_EXTS]
print(f"🖼️  Total images found: {len(all_images)}")

# ── Build global stem → label lookup ────────────────────────────
label_lookup = {
    p.stem: p
    for p in EXTRACT_DIR.rglob("*.txt")
    if p.name != "classes.txt"
}

# ── Match each image to its label ───────────────────────────────
pairs, missing = [], []

for img in all_images:
    stem = img.stem
    candidates = [
        img.with_suffix(".txt"),
        img.parent.parent / "labels" / f"{stem}.txt",
        img.parent / "labels"        / f"{stem}.txt",
        img.parent.parent.parent / "labels" / f"{stem}.txt",
    ]
    if stem in label_lookup:
        candidates.append(label_lookup[stem])

    label = next((c for c in candidates if c.exists()), None)
    if label:
        pairs.append((img, label))
    else:
        missing.append(img.name)

print(f"✅ Matched pairs : {len(pairs)}")
if missing:
    print(f"⚠️  Skipped (no label): {len(missing)} images")
    for m in missing:
        print(f"   • {m}")

# ── Split ────────────────────────────────────────────────────────
random.seed(RANDOM_SEED)
random.shuffle(pairs)
cut        = max(1, int(len(pairs) * TRAIN_RATIO))
train_pairs = pairs[:cut]
val_pairs   = pairs[cut:]
if not val_pairs and len(train_pairs) > 1:
    val_pairs = [train_pairs.pop()]

print(f"\n📂 Split  →  {len(train_pairs)} train  |  {len(val_pairs)} val")

# ── Copy into YOLO folder structure ─────────────────────────────
for split_name, split_pairs in [("train", train_pairs), ("val", val_pairs)]:
    img_dir = DATASET_DIR / "images" / split_name
    lbl_dir = DATASET_DIR / "labels" / split_name
    img_dir.mkdir(parents=True, exist_ok=True)
    lbl_dir.mkdir(parents=True, exist_ok=True)

    for img_src, lbl_src in split_pairs:
        shutil.copy2(img_src, img_dir / img_src.name)
        shutil.copy2(lbl_src, lbl_dir / lbl_src.name)

    print(f"   {split_name:5s}: {len(split_pairs):3d} images → {img_dir}")

print("\n✅ Dataset folder ready")

YAML_PATH = DATASET_DIR / "data.yaml"

config = {
    "path":  str(DATASET_DIR),
    "train": "images/train",
    "val":   "images/val",
    "nc":    len(CLASSES),
    "names": CLASSES,
}

with open(YAML_PATH, "w") as f:
    yaml.dump(config, f, default_flow_style=False, sort_keys=False)

print("📄 data.yaml:")
print(open(YAML_PATH).read())

print("🔍 Validating label files...")
issues = []

for split in ["train", "val"]:
    lbl_dir = DATASET_DIR / "labels" / split
    for lbl in lbl_dir.glob("*.txt"):
        for line_no, line in enumerate(open(lbl), 1):
            parts = line.strip().split()
            if not parts:
                continue
            try:
                cls_id = int(parts[0])
                if cls_id < 0 or cls_id >= len(CLASSES):
                    issues.append(f"{lbl.name}:{line_no} → class {cls_id} "
                                  f"out of range (0–{len(CLASSES)-1})")
                if len(parts) != 5:
                    issues.append(f"{lbl.name}:{line_no} → expected 5 values, "
                                  f"got {len(parts)}")
            except ValueError:
                issues.append(f"{lbl.name}:{line_no} → invalid line: {line.strip()}")

if issues:
    print(f"⚠️  {len(issues)} issue(s):")
    for i in issues: print(f"   • {i}")
else:
    print("✅ All label files are valid")

import cv2
import numpy as np

COLORS = [
    (255,  56,  56),   # crack         — red
    (255, 157,  51),   # scratch       — orange
    (255, 225,  51),   # rough_edge    — yellow
    (170,  51, 255),   # porosity      — purple
    ( 51, 153, 255),   # machining_burr— blue
]

def draw_boxes(img_path, lbl_path, classes, colors):
    img = cv2.imread(str(img_path))
    img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
    h, w = img.shape[:2]

    if lbl_path.exists():
        for line in open(lbl_path):
            parts = line.strip().split()
            if len(parts) != 5: continue
            cls_id = int(parts[0])
            cx, cy, bw, bh = map(float, parts[1:])
            x1 = int((cx - bw/2) * w)
            y1 = int((cy - bh/2) * h)
            x2 = int((cx + bw/2) * w)
            y2 = int((cy + bh/2) * h)
            color = colors[cls_id % len(colors)]
            cv2.rectangle(img, (x1,y1), (x2,y2), color, 2)
            label = classes[cls_id] if cls_id < len(classes) else str(cls_id)
            cv2.putText(img, label, (x1, y1-8),
                        cv2.FONT_HERSHEY_SIMPLEX, 0.6, color, 2)
    return img

# Show up to 6 training samples
train_imgs = sorted((DATASET_DIR/"images"/"train").glob("*"))[:6]
n = len(train_imgs)
cols = min(3, n)
rows = (n + cols - 1) // cols

fig, axes = plt.subplots(rows, cols, figsize=(6*cols, 5*rows))
axes = np.array(axes).flatten() if n > 1 else [axes]

for ax, img_path in zip(axes, train_imgs):
    lbl_path = DATASET_DIR / "labels" / "train" / img_path.with_suffix(".txt").name
    img = draw_boxes(img_path, lbl_path, CLASSES, COLORS)
    ax.imshow(img)
    ax.set_title(img_path.name, fontsize=9)
    ax.axis("off")

for ax in axes[n:]:       # hide empty subplots
    ax.axis("off")

plt.suptitle("Sample Training Images with Annotations", fontsize=13, y=1.01)
plt.tight_layout()
plt.show()
print("✅ Preview done")


# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# CELL 9 — TRAIN  🚀
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# @title Train YOLOv8
# @markdown **Settings — change if needed**

# ── Hyperparameters ──────────────────────────────────────────────
MODEL      = "yolov8n.pt"   # n=nano(fast) | s=small | m=medium | l=large
EPOCHS     = 100
IMG_SIZE   = 640
BATCH      = 8              # reduce to 4 if GPU runs out of memory
PROJECT    = "/content/runs"
RUN_NAME   = "pump_defect_v1"

from ultralytics import YOLO

print(f"🚀 Starting training...")
print(f"   Model   : {MODEL}")
print(f"   Epochs  : {EPOCHS}")
print(f"   Img size: {IMG_SIZE}")
print(f"   Batch   : {BATCH}")
print(f"   Classes : {CLASSES}\n")

model = YOLO(MODEL)

results = model.train(
    data    = str(YAML_PATH),
    epochs  = EPOCHS,
    imgsz   = IMG_SIZE,
    batch   = BATCH,
    project = PROJECT,
    name    = RUN_NAME,
    patience= 20,          # early stopping if no improvement for 20 epochs
    augment = True,        # built-in augmentation (flip, mosaic, hsv, etc.)
    verbose = True,
)

print("\n✅ Training complete!")
BEST_WEIGHTS = Path(PROJECT) / RUN_NAME / "weights" / "best.pt"
print(f"   Best weights: {BEST_WEIGHTS}")

model_eval = YOLO(str(BEST_WEIGHTS))
metrics    = model_eval.val(data=str(YAML_PATH))

print("\n📊 Validation Results:")
print(f"   mAP@50       : {metrics.box.map50:.4f}")
print(f"   mAP@50-95    : {metrics.box.map:.4f}")
print(f"   Precision    : {metrics.box.mp:.4f}")
print(f"   Recall       : {metrics.box.mr:.4f}")

# Per-class results
print("\n📋 Per-class mAP@50:")
for i, cls_name in enumerate(CLASSES):
    try:
        print(f"   {cls_name:20s}: {metrics.box.maps[i]:.4f}")
    except Exception:
        pass

results_png = Path(PROJECT) / RUN_NAME / "results.png"
if results_png.exists():
    display(Image(str(results_png)))
    print("📈 Training curves shown above")
else:
    print("⚠️  results.png not found yet — run training first")

val_imgs  = list((DATASET_DIR / "images" / "val").glob("*"))
inf_model = YOLO(str(BEST_WEIGHTS))

preds = inf_model.predict(
    source     = str(DATASET_DIR / "images" / "val"),
    conf       = 0.25,        # confidence threshold
    iou        = 0.45,        # NMS IOU threshold
    save       = True,
    project    = "/content/inference",
    name       = "val_preds",
)

# Show first 4 predictions
pred_dir = Path("/content/inference/val_preds")
pred_imgs = sorted(pred_dir.glob("*"))[:4]

fig, axes = plt.subplots(1, len(pred_imgs), figsize=(6*len(pred_imgs), 5))
if len(pred_imgs) == 1:
    axes = [axes]
for ax, p in zip(axes, pred_imgs):
    ax.imshow(mpimg.imread(str(p)))
    ax.set_title(p.name, fontsize=9)
    ax.axis("off")

plt.suptitle("Model Predictions on Validation Images", fontsize=13)
plt.tight_layout()
plt.show()
print("✅ Inference done")

print("📂 Upload a new pump image to test...")
test_upload = files.upload()
test_img    = list(test_upload.keys())[0]

inf_model = YOLO(str(BEST_WEIGHTS))
result     = inf_model.predict(
    source  = test_img,
    conf    = 0.25,
    save    = True,
    project = "/content/test_output",
    name    = "test",
)

# Display result
output_img = list(Path("/content/test_output/test").glob("*"))[0]
img = mpimg.imread(str(output_img))
plt.figure(figsize=(10, 8))
plt.imshow(img)
plt.axis("off")
plt.title("Defect Detection Result", fontsize=14)
plt.tight_layout()
plt.show()

print("\n🔍 Detected defects:")
for box in result[0].boxes:
    cls_id     = int(box.cls)
    confidence = float(box.conf)
    cls_name   = CLASSES[cls_id] if cls_id < len(CLASSES) else str(cls_id)
    print(f"   • {cls_name:20s}  confidence: {confidence:.2f}")